package game;

import java.awt.Graphics;

public class Stars extends Polygon{
	/*speed at which star background moves in response to player movement,
	 * const determines the "speed" of the parallax effect
	 * */
	private static double parallaxConst = 0.03;
	
	/*Star shape: initially was 5 point star, changed to three point star
	 * to reduce computation load with similar effect (stars too small to see
	 * a difference between 3 point and 5 point)
	 * 
	 * */
	private static Point[] starShape = { 
			/* 
			new Point(-1, 0), // A
			new Point(-0.4, 0), // B
			new Point(0, 0.75), // D
			new Point(0.4, 0), // E
			new Point(1, 0), // A'
			new Point(0.47, -0.3), // H
			new Point(0.75, -1), // C'
			new Point(0, -0.6), // G
			new Point(-0.74, -1), // C
			new Point(-0.45, -0.3) // F
			*/

			new Point(-1.5,0),
			new Point(0,3),
			new Point(1.5,0),

	};

	/*individiual shape of stars to be randomly generated by init block*/
	private Point[] indShape = new Point[starShape.length];

	/*randomly generates individual star size*/
	{
		for (int i = 0; i < starShape.length; i++) {
			indShape[i] = new Point(starShape[i].getX() * Math.random() * 3, 
					starShape[i].getY() * Math.random() * 3);

		}
	}	
	
	
	/**
	* star base constructor, calls polygon, uses randomly generated points
	*
	* @param  x star x coord, randomly generated
	* @param  y star y coord, randomly generated
	*/
	public Stars(int x, int y) {
		super(starShape, new Point(x, y), 0);
	}
	
/**
 * paint function called per tick, offsets each star in the opposite direction as 
 * ship at slower speed as determined by parallaxConst in order to replicate
 * parallax effect
 * 
 * @param g		graphics brush with color to draw shape
 * @param xVel	ship x velocity, used to calc parallax effect
 * @param yVel	ship y velocity, used to calc parallax effect
 */
	public void paint(Graphics g, double xVel, double yVel) {
		
		/* offsetCalc starOffset =  */
		//(position.getX(), xVel) -> position.setX(position.getX() - (xVel * 0.1));
		
		//position.setX(position.getX() - (xVel * 0.1));
		//position.setY(position.getY() - (yVel * 0.1));

		offsetCalc offsetX = vel -> position.setX(position.getX() - (vel * parallaxConst));
		offsetCalc offsetY = vel -> position.setY(position.getY() - (vel * parallaxConst));

		offsetX.starOffset(xVel);
		offsetY.starOffset(yVel);

		
		
		int[] x = new int[indShape.length];
		int[] y = new int[indShape.length];

		for (int i = 0; i < this.getPoints().length; i++) {
			x[i] = (int) this.getPoints()[i].getX();
			y[i] = (int) this.getPoints()[i].getY();
		}
		g.fillPolygon(x, y, indShape.length);

	}

}
